# Generated by Django 5.2.4 on 2025-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="slot_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
