# Generated by Django 5.2.4 on 2025-07-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_slot_end_appointment_slot_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="slot_end",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="slot_start",
        ),
    ]
