# Generated by Django 5.2.4 on 2025-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_merge_20250731_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnote",
            name="note_type",
            field=models.CharField(
                choices=[("D", "DOCTOR"), ("P", "PATIENT")], max_length=2
            ),
        ),
    ]
