# Generated by Django 5.2.4 on 2025-08-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_remove_appointment_slot_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="slot_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
